import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/layout/navBar'
import FeaturedEventCard from '@/components/home/featuredEventCard'
import Footer from '@/components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <FeaturedEventCard />
        <Footer />
        {children}
      </body>
    </html>
  )
}
